= nix-setup
Simon Holywell <simon@holywell.com.au>
:experimental:

== Getting started

Clone this repo to `~/.nixpkgs` and run the setup script:

[source,bash]
----
git clone git@github.com:treffynnon/nix-setup.git ~/.nixpkgs && ~/.nixpkgs/setup.sh
----

which will perform the following actions for you:

1. Install link:https://nixos.org/nix/download.html[nix]
1. if on a Mac install link:https://github.com/LnL7/nix-darwin#install[nix-darwin]
1. install link:https://rycee.gitlab.io/home-manager/index.html#sec-install-standalone[home-manager]
1. back-up `/etc/shells`
1. moves default ZSH zprofile and zshrc to *.local (they still get loaded!)
1. runs `darwin-rebuild switch` to install all the dependencies with nix

=== Setup bash completions

For bash completions to work properly the system must use the nix supplied version of bash as the MacOS version is ancient.

[source,bash]
----
chsh -s /run/current-system/sw/bin/bash
----

If you want to use Fish shell then:

[source,bash]
----
chsh -s /run/current-system/sw/bin/fish
----

See https://discourse.nixos.org/t/using-nix-to-install-login-shell-on-non-nixos-platform/2807/3

=== Setting up hammerspoon

Hammerspoon provides:

* Window management via the keyboard
* kbd:[Caps lock] as kbd:[Esc] when tapped and kbd:[Ctrl] when held

Run Hammerspoon (use Spotlight with kbd:[Command] + kbd:[Space]) and configure it to:

* Run at login
* Enable Accessibility
* (optionally) untick "Show dock icon"

The nix derivation that installs Hammerspoon it is in `./overlays/hammerspoon.nix` and the configuration is in `./home-configs/hammerspoon.nix` and `./home-configs/hammerspoon`.

== Making changes

If you modify any of the configurations in the nix configuration then you need to rebuild the environment.

[source,bash]
----
darwin-rebuild switch
----

It will probably ask you to enter a password, which can get annoying so you can modify the sudoers file to allow passwordless invocation of `darwin-rebuild` for your user.
Create a `/etc/sudoers.d/nix-darwin` file with this content:

[source, sudoers]
----
<home-user> ALL=(ALL:ALL) NOPASSWD: /run/current-system/sw/bin/darwin-rebuild (where home-user is name of home directory)
----

== Managing development environments

=== Direnv and Lorri

Install link:https://github.com/target/lorri[Lorri] (not currently a Nix package due to their rapid development cycles while in beta).

Put a .envrc file inside your project with:

..envrc
[source,sh]
----
eval "$(lorri direnv)"
----

and a file for the nix-shell (`shell.nix`):

[source,nix]
----
include::example-shell.nix[]
----

Start lorri with `lorri daemon` and leave it running in a shell.

Now when you cd into the projects directory Lorri/direnv will install the dependencies and drop you into a Nix shell.

== MacOS Catalina

Before upgrading to Catalina:

* https://gist.github.com/chrisandreae/e61e06f08ec0a650a0b3b41788d41724
* https://github.com/NixOS/nix/issues/2925

== References:

* https://github.com/nmattia/homies/blob/master/git/default.nix
* https://github.com/rummik/nixos-config/blob/master/config/nodejs.nix
* https://discourse.nixos.org/t/bootstrapping-new-system/3455/9
* https://nixos.org/nix/manual/#ssec-builtins
* https://rycee.gitlab.io/home-manager/options.html
* https://medium.com/@ejpcmac/about-using-nix-in-my-development-workflow-12422a1f2f4c
* https://github.com/direnv/direnv#setup
* https://wiki.nikitavoloboev.xyz/package-managers/nix/nix-darwin
* https://www.softinio.com/post/moving-from-homebrew-to-nix-package-manager/
* http://chriswarbo.net/git/nix-helpers/git/branches/master/index.html
* http://chriswarbo.net/projects/nixos/useful_hacks.html
* https://github.com/danieldk/nix-home/tree/master/cfg
* https://github.com/jwiegley/nix-config/blob/master/overlays/30-apps.nix
* https://github.com/Jomik/dotfiles/tree/master/.config/nixpkgs
* https://rycee.net/posts/2017-07-02-manage-your-home-with-nix.html

== Todo

* double check fzf configuration is OK now
* review possibility of fasd
* https://github.com/jasonrudolph/keyboard#features
