name: "Test"
on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: "Initial nix-shell run"
        run: nix develop --command "echo \"Initial run to get all the dependencies pulled down\""
        shell: bash

      - name: Check nix lint
        # see the flake file for where the lint-nix command comes from
        run: nix develop --command "lint-nix"
        shell: bash
      - name: Run nixpkgs-fmt check
        run: nix develop --command "ci-format-nix"
        shell: bash

      - name: Run luacheck
        run: nix develop --command "lint-lua"
        shell: bash
      - name: Run lua-format
        run: nix develop --command "format-lua"
        shell: bash
      - name: Check for changed files - fails if there is a git diff
        run: git diff --quiet
        shell: bash
