name: "Test"
on:
  pull_request:
  push:
jobs:
  format-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v3
      - uses: cachix/cachix-action@v2
        with:
          file: ci/nixpkgs-fmt.nix
          name: treffynnon
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # Only needed for private caches
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run nixpkgs-fmt check
        run: ./result/bin/nixpkgs-fmt --check ./**/*.nix
        shell: bash
  lint-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v3
      - uses: cachix/cachix-action@v2
        with:
          file: ci/nix-linter.nix
          name: treffynnon
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # Only needed for private caches
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run nix-linter check
        env:
          LC_ALL: en_US.UTF-8
        run: ./result/bin/nix-linter ./**/*.nix
        shell: bash
  format-lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v3
      - uses: cachix/cachix-action@v2
        with:
          file: ci/lua-format.nix
          name: treffynnon
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # Only needed for private caches
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run lua-format
        run: find home-configs/hammerspoon -type f -name "*.lua" -exec ./result/bin/lua-format {} +
        shell: bash
      - name: Check for changed files - fails if there is a git diff
        run: git diff --quiet
        shell: bash
  lint-hammerspoon-lua:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: fetch luacheck
        run: Invoke-WebRequest https://github.com/mpeterv/luacheck/releases/download/0.23.0/luacheck.exe -OutFile luacheck.exe
        shell: powershell
      - name: run luacheck
        run: Invoke-Expression '.\luacheck.exe --globals hs spoon --no-max-line-length home-configs\hammerspoon'
